#!/usr/bin/env python3
"""Generate overlay registration metadata from spec_parser output."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--segments",
        type=Path,
        default=Path(__file__).resolve().parent / "wr64_segments.json",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "docs" / "OVERLAY_RUNTIME.md",
    )
    args = parser.parse_args()

    data = json.loads(args.segments.read_text(encoding="utf-8"))
    segments = data["segments"] if isinstance(data, dict) else data
    overlays = [s for s in segments if s.get("is_overlay") or s.get("flags")]

    lines = [
        "# WR64 overlay runtime map",
        "",
        f"Total segments: {len(segments)}",
        f"Overlay-like segments: {len(overlays)}",
        "",
        "Runtime uses `RecompiledFuncs/recomp_overlays.inl` generated by N64Recomp.",
        "Relocatable prog/course/bank segments are listed in `overlays.us.txt`.",
        "",
        "| Segment | VRAM | Size | Flags |",
        "| --- | --- | --- | --- |",
    ]

    for seg in overlays[:200]:
        vram = seg.get("vram")
        vram_s = f"0x{vram:08X}" if isinstance(vram, int) and vram > 0x1000 else str(vram)
        flags = ",".join(seg.get("flags", []))
        lines.append(f"| {seg['name']} | {vram_s} | {seg.get('size', 0)} | {flags} |")

    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
